server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book/**
        - id: pet-service
          uri: lb://pet-service
          predicates:
            - Path=/pet/**
        - id: asistencia-service
          uri: lb://asistencia-service
          predicates:
            - Path=/asistencia/**
        - id: documento-service
          uri: lb://documento-service
          predicates:
            - Path=/documento/**
        - id: trabajador-service
          uri: lb://trabajador-service
          predicates:
            - Path=/empleado/**            
